### ISSUE TITLE
Client and Server rendering

### ISSUE THREAD

**Issue by ghost** [ayoubdev/reactjs-starterkit#2]
Hi @ayoubdev

Would be great to have the server and client side rendering at the same time.

As it's well separated now I look like a bit tricky, but possible :-)

**Comment by ghost** [comment]
maybe using concurrently to launch the svr and the client at the same time, while using a script tag inside the svr rendering ?

**Comment by adbayb** [comment]
Hello @naptiv ,

It can be done. What you need to do is to allow the first request made by the browser to be managed by the server while subsequent requests are processed by the client. 
For this, like you said, including a script tag (that manages your client side) inside the server rendering html body's end can solve your problem (see renderHTML function https://github.com/ayoubdev/reactjs-isomorphic-starterkit/blob/master/src/server/index.jsx)

**Comment by ghost** [comment]
Docker maid the job like a charm :+1:
